### ISSUE TITLE
German keyboard layout wrong

### ISSUE THREAD

**Issue by adnidor** [MarZab/FxKeyboard#18]
With the german keyboard layout the y key is showing as a z key
![g4268](https://cloud.githubusercontent.com/assets/4891425/9083469/c5b29f60-3b6a-11e5-9b82-cdb779bc4cf0.png)

**Comment by MarZab** [comment]
693d66973efabd22439a31dd2952dc3412a092f3 fixes this

**Comment by MarZab** [comment]
if you want to help make a better layout for german, you can edit this file https://github.com/MarZab/FxKeyboard/blob/master/src/chrome/content/locales.js#L79 and do a pull request
