### ISSUE TITLE
Please add russian lang

### ISSUE THREAD

**Issue by Murlika** [MarZab/FxKeyboard#19]
That version is very well! But please add ru-RU locale

**Comment by MarZab** [comment]
Can you take this file, edit the english or add a new section and send it back to me?

https://github.com/MarZab/FxKeyboard/blob/master/src/chrome/content/locales.js

**Comment by Murlika** [comment]
Hello!It's my file with russian lang  06.08.2015, 22:32, "Marko Zabreznik" <notifications@github.com>:Can you take this file, edit the english or add a new section and send it back to me?https://github.com/MarZab/FxKeyboard/blob/master/src/chrome/content/locales.js—Reply to this email directly or view it on GitHub.

**Comment by MarZab** [comment]
Sorry, attachments dont work with emailing to github, can you respond with a gist link or pastebin link, or upload here https://github.com/MarZab/FxKeyboard/issues/19#issuecomment-133027650

**Comment by Murlika** [comment]
Ok, here it is http://pastebin.com/5aSWMAma

**Comment by MarZab** [comment]
doesn't russian need commas and question marks ? :confused:
