### ISSUE TITLE
Tab key

### ISSUE THREAD

**Issue by cartmen** [MarZab/FxKeyboard#2]
Is there a possible chance that you add a tabulator key to FxKeyboard? It would be really great.

**Comment by MarZab** [comment]
Here is a sample of how a not so clever solution:

    doTab: function () {

        var inputs = ((fxKeyboard.focus || {}).ownerDocument || {}).querySelectorAll('input,textarea');
        if (inputs) {
            for (var i = 0; i < inputs.length; i++) {
                if (inputs[i] === fxKeyboard.focus) {
                    // ok, focus next one
                    inputs[i + 1].focus();
                    break;
                }
            }
        }

    }

**Comment by MarZab** [comment]
Version 3 has this integrated, closing the issue.
