### ISSUE TITLE
icons not shown

### ISSUE THREAD

**Issue by 1u** [MarZab/FxKeyboard#22]
"toggle locale" and "Keep open" load wrong icons. all other characters in all langs are fine, as well special ones and with shift.

Firefox 43.0 on Ubuntu

![fxkeyboard_bug](https://cloud.githubusercontent.com/assets/4281072/12058983/12dca20c-af53-11e5-8d1f-ac36c47a02a6.png) ... ![del](https://cloud.githubusercontent.com/assets/4281072/12059035/fc8bbc8a-af53-11e5-9f09-0e7d02b4e5c7.png)

**Comment by MarZab** [comment]
the problem is with the font, you need a font that has the right gliphs
you can change the layout in the locales.js if you need as well
