### ISSUE TITLE
Numlock? 

### ISSUE THREAD

**Issue by LucasVollebergh** [MarZab/FxKeyboard#23]
Hi,

Is there a posibility to lock the numbers (like on an iPhone) for multiple number use? 
If you want to type 1234567890 you always have to select the number pad.

<img width="125" alt="schermafbeelding 2016-06-14 om 17 30 07" src="https://cloud.githubusercontent.com/assets/13552277/16048800/a8a0a060-3255-11e6-99e8-408e7854631b.png">

**Comment by MarZab** [comment]
Click it 2 times to lock.
14. jun. 2016 17:30 je oseba "LucasVollebergh" <notifications@github.com>
napisala:

**Comment by LucasVollebergh** [comment]
Oh... Embarrassing.. So easy. :) 
Thanks! 👍
